## Submit script for processing multiple years of smoke data
## as a distributed process. This script calls the files generated by
## run_batch_bluesky.sh, which allocates a month of data to each node.
## Data is processed by proc_bluesky_daily.R

#!/bin/bash -l
#$ -q all.q
#$ -N bluesky_hrly.err
#$ -cwd
#$ -j y
#$ -S /bin/bash
#$ -t 01-12:1
## load module
source /etc/profile.d/modules.sh
module load R/3.6.1
#
Rscript proc_bluesky_daily.R bluesky$SGE_TASK_ID ~/data/wildfire_data/NAM4km_data ~/outputs/wf_out/bluesky4km

